### ISSUE TITLE
synthtext预训练报错，item出现out of range

### ISSUE THREAD

**Issue by HanazawaKanana** [GXYM/TextBPN-Plus-Plus#29]
==========Options============
means: [0.485, 0.456, 0.406]
stds: [0.229, 0.224, 0.225]
gpu: 0
exp_name: Synthtext
num_workers: 12
batch_size: 12
max_epoch: 1
start_epoch: 0
lr: 0.001
cuda: True
output_dir: output
input_size: 640
max_annotation: 64
adj_num: 4
num_points: 20
use_hard: True
load_memory: False
scale: 4
grad_clip: 25
dis_threshold: 0.35
cls_threshold: 0.875
approx_factor: 0.004
resume: None
mgpu: False
save_dir: ./model/
vis_dir: ./vis/
log_dir: ./logs/
loss: CrossEntropyLoss
pretrain: False
verbose: True
viz: False
lr_adjust: fix
stepvalues: []
weight_decay: 0.0
gamma: 0.1
momentum: 0.9
optim: Adam
save_freq: 1
display_freq: 10
viz_freq: 50
log_freq: 10000
val_freq: 1000
net: resnet18
rescale: 255.0
test_size: [640, 960]
checkepoch: 1070
img_root: None
device: cuda
=============End=============
858750
858750
858750
load the resnet18 weight from ./cache
torch.Size([1, 400, 2])
Start training TextBPN++.
Epoch: 0 : LR = [0.001]
858750
-4839622111495562228
item: -4839622111495562228
4417196306718568984
item: 4417196306718568984
-4933052517224361324
item: -4933052517224361324
4336763268751199933
item: 4336763268751199933
-4860068110067164850
item: -4860068110067164850
4382889117272481807
item: 4382889117272481807
4372841479352437913
item: 4372841479352437913
4126157183006913079
item: 4126157183006913079
-4866316114929511829
item: -4866316114929511829
4329338288207398613
item: 4329338288207398613
4361680109188977151
item: 4361680109188977151
-4833282082644725854
4410336853102326262
item: -4833282082644725854
item: 4410336853102326262
4340354028912819191
-4882812270444156328
item: 4340354028912819191
item: -4882812270444156328
4389063076922214858
-4855495352855003913
item: 4389063076922214858
item: -4855495352855003913
4337034921130947313
item: 4337034921130947313
4291565715118546169
item: 4291565715118546169
-5032344146712329096
item: -5032344146712329096
4380753002384525029
item: 4380753002384525029
4273879802089765436
item: 4273879802089765436
-4812784359810025232
item: -4812784359810025232
Traceback (most recent call last):
-4898142501203486954
item: -4898142501203486954
  File "train_textBPN.py", line 296, in <module>
    main()
  File "train_textBPN.py", line 277, in main
-4864736833982383315
item: -4864736833982383315
    train(model, train_loader, criterion, scheduler, optimizer, epoch)
  File "train_textBPN.py", line 83, in train
    for i, inputs in enumerate(train_loader):
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sibao/桌面/实验代码/TextBPN-Plus-Plus/synth_text.py", line 69, in __getitem__
    data = self.load_img_gt(item)
  File "/home/sibao/桌面/实验代码/TextBPN-Plus-Plus/synth_text.py", line 47, in load_img_gt
    annotation_id = self.annotation_list[item]
IndexError: list index out of range

**Comment by GXYM** [comment]
> ==========Options============ means: [0.485, 0.456, 0.406] stds: [0.229, 0.224, 0.225] gpu: 0 exp_name: Synthtext num_workers: 12 batch_size: 12 max_epoch: 1 start_epoch: 0 lr: 0.001 cuda: True output_dir: output input_size: 640 max_annotation: 64 adj_num: 4 num_points: 20 use_hard: True load_memory: False scale: 4 grad_clip: 25 dis_threshold: 0.35 cls_threshold: 0.875 approx_factor: 0.004 resume: None mgpu: False save_dir: ./model/ vis_dir: ./vis/ log_dir: ./logs/ loss: CrossEntropyLoss pretrain: False verbose: True viz: False lr_adjust: fix stepvalues: [] weight_decay: 0.0 gamma: 0.1 momentum: 0.9 optim: Adam save_freq: 1 display_freq: 10 viz_freq: 50 log_freq: 10000 val_freq: 1000 net: resnet18 rescale: 255.0 test_size: [640, 960] checkepoch: 1070 img_root: None device: cuda =============End============= 858750 858750 858750 load the resnet18 weight from ./cache torch.Size([1, 400, 2]) Start training TextBPN++. Epoch: 0 : LR = [0.001] 858750 -4839622111495562228 item: -4839622111495562228 4417196306718568984 item: 4417196306718568984 -4933052517224361324 item: -4933052517224361324 4336763268751199933 item: 4336763268751199933 -4860068110067164850 item: -4860068110067164850 4382889117272481807 item: 4382889117272481807 4372841479352437913 item: 4372841479352437913 4126157183006913079 item: 4126157183006913079 -4866316114929511829 item: -4866316114929511829 4329338288207398613 item: 4329338288207398613 4361680109188977151 item: 4361680109188977151 -4833282082644725854 4410336853102326262 item: -4833282082644725854 item: 4410336853102326262 4340354028912819191 -4882812270444156328 item: 4340354028912819191 item: -4882812270444156328 4389063076922214858 -4855495352855003913 item: 4389063076922214858 item: -4855495352855003913 4337034921130947313 item: 4337034921130947313 4291565715118546169 item: 4291565715118546169 -5032344146712329096 item: -5032344146712329096 4380753002384525029 item: 4380753002384525029 4273879802089765436 item: 4273879802089765436 -4812784359810025232 item: -4812784359810025232 Traceback (most recent call last): -4898142501203486954 item: -4898142501203486954 File "train_textBPN.py", line 296, in main() File "train_textBPN.py", line 277, in main -4864736833982383315 item: -4864736833982383315 train(model, train_loader, criterion, scheduler, optimizer, epoch) File "train_textBPN.py", line 83, in train for i, inputs in enumerate(train_loader): File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in **next** data = self._next_data() File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data return self._process_data(data) File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data data.reraise() File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise raise self.exc_type(msg) IndexError: Caught IndexError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop data = fetcher.fetch(index) File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/sibao/anaconda3/envs/torch17/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/sibao/桌面/实验代码/TextBPN-Plus-Plus/synth_text.py", line 69, in **getitem** data = self.load_img_gt(item) File "/home/sibao/桌面/实验代码/TextBPN-Plus-Plus/synth_text.py", line 47, in load_img_gt annotation_id = self.annotation_list[item] IndexError: list index out of range

你这个问题我不知为啥，没有遇到过，这是dataloader取数据，搞不懂你的索引为啥是个负的，还这么大
